# Generated by Django 3.1.1 on 2020-10-02 11:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('voicedb', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prices',
            name='item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='voicedb.items'),
        ),
    ]
